### ISSUE TITLE
Variables not getting to scss files

### ISSUE THREAD

**Issue by IAMtheIAM** [epegzz/sass-vars-loader#19]
After I got the issue resolved in https://github.com/epegzz/sass-vars-loader/issues/18, now the variables are not getting passed to any .scss files.

```
Undefined variable: "$env".
```
sass-js-vars.js

```
module.exports = {
      env: METADATA.ENV, // doesnt work even thought this value exists
};
```

scss file
```scss
// Set the default environment for all scss files to refer to
$dev: false;

// Env variable - coming from Sass-Vars-Loader
@if $env == 'development' {
   $dev: true;
}
```
Worked fine in 2.x, not 3.x

If i switch to 

```
const sassVarsConfig = {
   syntax: 'scss',
   vars : {
      env: METADATA.ENV,
   } 
};
```
The error is the same, for some reason its not getting passed into my scss files. Any ideas?
